{
  "formatVersion": "1.1",
  "component": {
    "group": "gregtech",
    "module": "gregtech",
    "version": "2.9.0-oganesson",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "zone.rong",
          "module": "mixinbooter",
          "version": {
            "requires": "10.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "codechicken",
          "module": "codechickenlib",
          "version": {
            "requires": "3.2.3.358"
          }
        },
        {
          "group": "com.cleanroommc",
          "module": "modularui",
          "version": {
            "requires": "2.5.0-rc4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.cleanroommc",
          "module": "groovyscript",
          "version": {
            "requires": "1.2.0-hotfix1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "inventory-bogosorter-632327",
          "version": {
            "requires": "4951607-deobf-4951608-sources-4951609"
          }
        },
        {
          "group": "CraftTweaker2",
          "module": "CraftTweaker2-MC1120-Main",
          "version": {
            "requires": "1.12-4.1.20.700"
          }
        },
        {
          "group": "appeng",
          "module": "ae2-uel",
          "version": {
            "requires": "v0.56.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "ctm-267602",
          "version": {
            "requires": "2915363"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "gregtech-2.9.0-oganesson-dev.jar",
          "url": "gregtech-2.9.0-oganesson-dev.jar",
          "size": 13760875,
          "sha512": "cded95e2599f3294e72da9f869c7faef48b7a42452b31aebbc0db33d33aba036cd3f0274ccc11473d0f805d44d66f3575ff5e78b1e787903086457a536b164fc",
          "sha256": "aa0a07d6139d785da2875e7d3b3e2c6faf79594a75f7758586c1addb8cedb147",
          "sha1": "b182c4e7c4c065ef33fc462cd35a5696a3c7a237",
          "md5": "5af0604bfc7831434d65f5858279759a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei_1.12.2",
          "version": {
            "requires": "4.16.1.302"
          }
        },
        {
          "group": "curse.maven",
          "module": "top-245211",
          "version": {
            "requires": "2667280"
          }
        },
        {
          "group": "zone.rong",
          "module": "mixinbooter",
          "version": {
            "requires": "10.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "codechicken",
          "module": "codechickenlib",
          "version": {
            "requires": "3.2.3.358"
          }
        },
        {
          "group": "com.cleanroommc",
          "module": "modularui",
          "version": {
            "requires": "2.5.0-rc4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.cleanroommc",
          "module": "groovyscript",
          "version": {
            "requires": "1.2.0-hotfix1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "inventory-bogosorter-632327",
          "version": {
            "requires": "4951607-deobf-4951608-sources-4951609"
          }
        },
        {
          "group": "CraftTweaker2",
          "module": "CraftTweaker2-MC1120-Main",
          "version": {
            "requires": "1.12-4.1.20.700"
          }
        },
        {
          "group": "appeng",
          "module": "ae2-uel",
          "version": {
            "requires": "v0.56.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "ctm-267602",
          "version": {
            "requires": "2915363"
          }
        }
      ],
      "files": [
        {
          "name": "gregtech-2.9.0-oganesson-dev.jar",
          "url": "gregtech-2.9.0-oganesson-dev.jar",
          "size": 13760875,
          "sha512": "cded95e2599f3294e72da9f869c7faef48b7a42452b31aebbc0db33d33aba036cd3f0274ccc11473d0f805d44d66f3575ff5e78b1e787903086457a536b164fc",
          "sha256": "aa0a07d6139d785da2875e7d3b3e2c6faf79594a75f7758586c1addb8cedb147",
          "sha1": "b182c4e7c4c065ef33fc462cd35a5696a3c7a237",
          "md5": "5af0604bfc7831434d65f5858279759a"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gregtech-2.9.0-oganesson.jar",
          "url": "gregtech-2.9.0-oganesson.jar",
          "size": 13866617,
          "sha512": "5637e6adc43d448e76c4a1b3b7313e5d9ba026a79893e8089c9e096332083e39a6b8e69d5498534414a824934af3b801b275200412e8afdff7c1b108c92b6d26",
          "sha256": "150f192721bc4731b8273ab142e406d23fb4d6852ea4fec5753461d521d97acb",
          "sha1": "2da9c249086e0e036d86533ac2029a71a5da9c99",
          "md5": "d4b4315a9a827852f5d98412c1797db4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gregtech-2.9.0-oganesson-sources.jar",
          "url": "gregtech-2.9.0-oganesson-sources.jar",
          "size": 11210937,
          "sha512": "266908d5c2bf152ffa19906e6333b0b63b5b86fe3afe66cfda9dfbfeae5aa16107f6b4a75f709a561556b0bed8b7781d4b5639ba84075ade30f9b567357125a8",
          "sha256": "cdd1fb3acdb1a2703494c4b1706815180dca07f52ca233dac7bcf05da284cb5b",
          "sha1": "f2496ddd80834c2f8630a7bd1c31d1d20cd4845c",
          "md5": "b3e82a976b77c1a662993063e53232cb"
        }
      ]
    }
  ]
}
