on:
  push:
    branches:
      - sync/upstream/master
  workflow_dispatch:
      inputs:
        branch:
          description: 'branch'
          default: 'sync/upstream/master'
  pull_request:


concurrency:
  group: publish-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Build
        uses: ./.github/actions/build_setup

      - name: Build Project
        run: ./gradlew build --warning-mode all --build-cache

      - name: Publish to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: "build/libs/*.jar"
          fail_on_unmatched_files: true
          prerelease: true
          tag_name: "${{ env.COMMIT_SHORT_SHA }}"
          name: "Test Building ${{ env.COMMIT_SHORT_SHA }}"
          body: "Testing GregTech CEu 2.9 Preview"
