on:
  push:
    branches:
      - sync/upstream/master
  workflow_dispatch:
      inputs:
        branch:
          description: 'branch'
          default: 'sync/upstream/master'
  pull_request:


concurrency:
  group: publish-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Build
        uses: ./.github/actions/build_setup

      - name: Build Project
        run: ./gradlew build --warning-mode all --build-cache

      - name: Package Artifacts
        shell: bash
        run: |
          zip -r build/artifacts.zip build/libs/
          

      - name: Upload Default Jar
        uses: actions/upload-artifact@v4.4.0
        with:
            name: ${{ env.COMMIT_SHORT_SHA }}
            path: build/artifacts.zip
