on:
  push:
    branches:
      - sync/upstream/master
  workflow_dispatch:
      inputs:
        branch:
          description: 'branch'
          default: 'sync/upstream/master'
  pull_request:


concurrency:
  group: publish-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Build
        uses: ./.github/actions/build_setup

      - name: Build Project
        run: ./gradlew build --warning-mode all --build-cache

      - name: Upload Default Jar
        uses: actions/upload-artifact@v4.4.0
        with:
            name: default jar
            path: build/libs/*-oganesson.jar

      - name: Upload Sources Jar
        uses: actions/upload-artifact@v4.4.0
        with:
            name: sources jar
            path: build/libs/*-sources.jar

      - name: Upload Dev Jar
        uses: actions/upload-artifact@v4.4.0
        with:
            name: dev jar
            path: build/libs/*-dev.jar
